export const ADD_TODO = 'ADD_TODO'
export const GET_DATA = 'GET_DATA'
export const IS_ADMIN = 'IS_ADMIN'
export const SET_LOADING = 'SET_LOADING'
export const DELETE_TODO = 'DELETE_TODO'
export const CHANGE_TODO = 'CHANGE_TODO'
export const EDIT_LOCAL_TODO = 'EDIT_LOCAL_TODO'